# Generated by Django 4.1.2 on 2022-10-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NID", models.CharField(max_length=15)),
                ("TITLE", models.CharField(max_length=50)),
                ("F_NAME", models.CharField(max_length=150)),
                ("L_NAME", models.CharField(max_length=150)),
                ("BIRTH_DATE", models.CharField(blank=True, max_length=36, null=True)),
                ("HOUSE_CODE", models.CharField(max_length=10)),
                (
                    "SEX_CARD",
                    models.CharField(
                        choices=[("1", "หญิง"), ("2", "ชาย")], max_length=1
                    ),
                ),
                ("BODY_CODE", models.CharField(max_length=1)),
                (
                    "DISABLED_CODE",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("KEEPER_CODE", models.CharField(blank=True, max_length=1, null=True)),
                ("CURATOR_CODE", models.CharField(blank=True, max_length=1, null=True)),
                ("PHONE_MOBILE", models.CharField(max_length=10)),
            ],
            options={"verbose_name": "People", "verbose_name_plural": "Peoples",},
        ),
    ]
