# Generated by Django 4.1.2 on 2022-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agovdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='HOUSE_CODE',
            field=models.CharField(max_length=11),
        ),
    ]
