# Generated by Django 4.1.2 on 2022-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agovdata', '0002_alter_people_house_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='HOUSE_CODE',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
