# Generated by Django 4.1.2 on 2022-10-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agovdata', '0003_alter_people_house_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='PHONE_MOBILE',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
