# Generated by Django 4.1.2 on 2022-10-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agovdata', '0004_alter_people_phone_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='NID',
            field=models.CharField(max_length=15, verbose_name='Nid'),
        ),
    ]
