# Generated by Django 4.1.2 on 2022-10-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agovdata', '0005_alter_people_nid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ('-NID',), 'verbose_name': 'People', 'verbose_name_plural': 'Peoples'},
        ),
    ]
